// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demo01.Models;

namespace demo01.Migrations
{
    [DbContext(typeof(KSContext))]
    [Migration("20190408050058_Initail")]
    partial class Initail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("demo01.Record", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Add");

                    b.Property<DateTimeOffset>("Changetime");

                    b.Property<long>("Class1");

                    b.Property<long?>("Class2");

                    b.Property<string>("Description");

                    b.Property<int>("Gov");

                    b.Property<long?>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("Opentime");

                    b.Property<string>("ParkinginfoPx");

                    b.Property<string>("ParkinginfoPy");

                    b.Property<string>("Picdescribe1");

                    b.Property<string>("Picture1");

                    b.Property<string>("Px");

                    b.Property<string>("Py");

                    b.Property<long>("RecordId");

                    b.Property<string>("Remarks");

                    b.Property<string>("Tel");

                    b.Property<int>("Ticketinfo");

                    b.Property<string>("Toldescribe");

                    b.Property<string>("Travellinginfo");

                    b.Property<string>("Website");

                    b.Property<string>("Zone");

                    b.HasKey("Id");

                    b.ToTable("ScenicSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
